/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.directorio_amigos;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class Ventana_principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_principal.class.getName());

    private static final String RUTA_ARCHIVO =
        "entrega_5/directorio_amigos/src/main/java/com/mycompany/directorio_amigos/files/archivo_directorio.txt";

    private final FriendRepository repositorio;

    /**
     * Creates new form Ventana_principal
     */
    public Ventana_principal() {
        initComponents();
        repositorio = new FriendRepository(RUTA_ARCHIVO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        label_numero = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        campo_numero = new javax.swing.JTextField();
        boton_crear = new javax.swing.JButton();
        boton_leer = new javax.swing.JButton();
        boton_actualizar = new javax.swing.JButton();
        boton_borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_mensajes = new javax.swing.JTextArea();
        boton_limpiarMensajes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_limpiarCeldas = new javax.swing.JButton();
        boton_limpiarNombre = new javax.swing.JButton();
        boton_limpiarNumero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nombre.setText("Nombre");

        label_numero.setText("Número");

        boton_crear.setText("Crear");
        boton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearActionPerformed(evt);
            }
        });

        boton_leer.setText("Leer");
        boton_leer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton_leerActionPerformed(evt);
        }
        });

        boton_actualizar.setText("Actualizar");
        boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton_actualizarActionPerformed(evt);
       }
      });

        boton_borrar.setText("Borrar");
        boton_borrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton_borrarActionPerformed(evt);
        }
        });



        area_mensajes.setColumns(20);
        area_mensajes.setRows(5);
        jScrollPane1.setViewportView(area_mensajes);

        boton_limpiarMensajes.setText("Limpiar mensajes");
        boton_limpiarMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarMensajesActionPerformed(evt);
            }
        });

        jLabel1.setText("Historial de acciones");

        boton_limpiarCeldas.setText("Limpiar celdas");
        boton_limpiarCeldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarCeldasActionPerformed(evt);
            }
        });

        boton_limpiarNombre.setText("Limpiar");
        boton_limpiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarNombreActionPerformed(evt);
            }
        });

        boton_limpiarNumero.setText("Limpiar");
        boton_limpiarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nombre)
                                    .addComponent(label_numero))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campo_nombre)
                                    .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_limpiarNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boton_limpiarNumero, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton_crear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_leer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_borrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_limpiarCeldas))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(boton_limpiarMensajes)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_limpiarNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numero)
                    .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_limpiarNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_crear)
                    .addComponent(boton_leer)
                    .addComponent(boton_actualizar)
                    .addComponent(boton_borrar)
                    .addComponent(boton_limpiarCeldas))
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_limpiarMensajes)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearActionPerformed
    String nombreIngresado = campo_nombre.getText().trim();
    String numeroTexto = campo_numero.getText().trim();

    if (nombreIngresado.isEmpty() || numeroTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor complete ambos campos antes de agregar un amigo al directorio.");
        area_mensajes.append("\nError: campos vacíos.\n");
        return;
    }

    if (!numeroTexto.matches("\\d+")) {
        JOptionPane.showMessageDialog(this,
                "El número debe contener solo dígitos.");
        area_mensajes.append("\nError: el número debe contener solo dígitos.\n");
        return;
    }

    try {
        long numero = Long.parseLong(numeroTexto);
        Friend nuevo = new Friend(nombreIngresado, numero);

        boolean agregado = repositorio.agregar(nuevo);

        if (agregado) {
            JOptionPane.showMessageDialog(this,
                    "Amigo agregado al directorio correctamente.");
            area_mensajes.append("\n" + nuevo + " agregado correctamente.\n");
            campo_nombre.setText("");
            campo_numero.setText("");
        } else {
            JOptionPane.showMessageDialog(this,
                    "El nombre o el número ya existen en el directorio.");
            area_mensajes.append("\nError: el nombre o el número ya existen en el directorio.\n");
        }

    } catch (IOException ioe) {
        JOptionPane.showMessageDialog(this,
                "Ha ocurrido un error al acceder al archivo.");
        area_mensajes.append("\nError: al acceder al archivo.\n");
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this,
                "Ha ocurrido un error con el formato del número.");
        area_mensajes.append("\nError: formato de número inválido.\n");
    }
    }//GEN-LAST:event_boton_crearActionPerformed


    private void boton_limpiarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarMensajesActionPerformed
        area_mensajes.setText("");        
    }//GEN-LAST:event_boton_limpiarMensajesActionPerformed

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String nombreIngresado = campo_nombre.getText().trim();
        String numeroTexto = campo_numero.getText().trim();

        if (nombreIngresado.isEmpty() || numeroTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Para actualizar debe ingresar NOMBRE y el NUEVO NÚMERO.");
            area_mensajes.append("\nError: faltan campos.\n");
            return;
        }

        if (!numeroTexto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,
                    "El número debe contener solo dígitos.");
            area_mensajes.append("\nError: el número debe contener solo dígitos.\n");
            return;
        }

        try {
            long nuevoNumero = Long.parseLong(numeroTexto);
            boolean actualizado = repositorio.actualizarNumero(nombreIngresado, nuevoNumero);

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Número actualizado correctamente.");
                area_mensajes.append("\nNúmero actualizado para " + nombreIngresado +
                                     " -> " + nuevoNumero + "\n");
            } else {
                JOptionPane.showMessageDialog(this, "Amigo no encontrado en el directorio.");
                area_mensajes.append("\nAmigo no encontrado.\n");
            }
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error al acceder al archivo.");
            area_mensajes.append("\nError: al acceder al archivo.\n");
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error con el formato del número.");
            area_mensajes.append("\nError: formato de número inválido.\n");
        }
    } 

    private void boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String nombreIngresado = campo_nombre.getText().trim();
        String numeroTexto = campo_numero.getText().trim();

        if ((nombreIngresado.isEmpty() && numeroTexto.isEmpty()) ||
            (!nombreIngresado.isEmpty() && !numeroTexto.isEmpty())) {

            JOptionPane.showMessageDialog(this,"Para borrar por nombre ingrese solo el nombre,\n" + "para borrar por número ingrese solo el número.");
            area_mensajes.append("\nError: Para borrar use solo un campo (nombre o número).\n");
            return;
        }

        if (!numeroTexto.isEmpty() && !numeroTexto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,
                    "El número debe contener solo dígitos.");
            area_mensajes.append("\nError: El número debe contener solo dígitos.\n");
            return;
        }

        try {
            boolean borrado;

            if (!nombreIngresado.isEmpty()) {
                borrado = repositorio.borrarPorNombre(nombreIngresado);
            } else {
                long numero = Long.parseLong(numeroTexto);
                borrado = repositorio.borrarPorNumero(numero);
            }

            if (borrado) {
                JOptionPane.showMessageDialog(this, "Contacto borrado del directorio.");
                area_mensajes.append("\nContacto borrado del directorio.\n");
            } else {
                JOptionPane.showMessageDialog(this, "Amigo no encontrado en el directorio.");
                area_mensajes.append("\nAmigo no encontrado en el directorio.\n");
            }

        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error al acceder al archivo.");
            area_mensajes.append("\nError: Ha ocurrido un error al acceder al archivo.\n");
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error con el formato del número.");
            area_mensajes.append("\nError: Ha ocurrido un error con el formato del número.\n");
        }
    }

    private void boton_limpiarCeldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarCeldasActionPerformed
        campo_nombre.setText("");
        campo_numero.setText("");
    }//GEN-LAST:event_boton_limpiarCeldasActionPerformed

    private void boton_leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_leerActionPerformed
        String nombreIngresado = campo_nombre.getText().trim();
        String numeroTexto = campo_numero.getText().trim();

        if (!(nombreIngresado.isEmpty() ^ numeroTexto.isEmpty())) {
            JOptionPane.showMessageDialog(this,
                    "Para buscar por nombre ingrese solo el nombre, para buscar por número ingrese solo el número.");
            return;
        }

        try {
            Friend encontrado = null;

            if (!nombreIngresado.isEmpty()) {
                encontrado = repositorio.buscarPorNombre(nombreIngresado);
            } else {
                if (!numeroTexto.matches("\\d+")) {
                    JOptionPane.showMessageDialog(this,
                            "El número debe contener solo dígitos.");
                    area_mensajes.append("\nError: el número debe contener solo dígitos.\n");
                    return;
                }
                long numero = Long.parseLong(numeroTexto);
                encontrado = repositorio.buscarPorNumero(numero);
            }

            if (encontrado != null) {
                JOptionPane.showMessageDialog(this, "Amigo encontrado en el directorio.");
                area_mensajes.append("\nAmigo encontrado en el directorio.\n");
                area_mensajes.append(encontrado.toString() + "\n");
            } else {
                JOptionPane.showMessageDialog(this, "Amigo no encontrado en el directorio.");
                area_mensajes.append("\nAmigo no encontrado en el directorio.\n");
            }

        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error al acceder al archivo.");
            area_mensajes.append("\nError: al acceder al archivo.\n");
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error con el formato del número.");
            area_mensajes.append("\nError: formato de número inválido.\n");
        } 
    }//GEN-LAST:event_boton_leerActionPerformed

    private void boton_limpiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarNombreActionPerformed
        campo_nombre.setText("");
    }//GEN-LAST:event_boton_limpiarNombreActionPerformed

    private void boton_limpiarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarNumeroActionPerformed
        campo_numero.setText("");
    }//GEN-LAST:event_boton_limpiarNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Ventana_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_mensajes;
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_crear;
    private javax.swing.JButton boton_leer;
    private javax.swing.JButton boton_limpiarCeldas;
    private javax.swing.JButton boton_limpiarMensajes;
    private javax.swing.JButton boton_limpiarNombre;
    private javax.swing.JButton boton_limpiarNumero;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_numero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_numero;
    // End of variables declaration//GEN-END:variables
}
